#!/usr/bin/env bash
set -euo pipefail

# Format staged Go files with goimports and include the results in this commit.
go_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

if [ -n "$go_files" ]; then
  golangci-lint fmt ./...
  git add -- $go_files

  # Test and lint the module to catch errors before committing.
  go test ./...
  golangci-lint run ./...
fi

# Auto-fix and format staged Dart files and include the results in this commit.
dart_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.dart')

if [ -n "$dart_files" ]; then
  # Call the SDK binaries directly, as using FVM in this script is unreliable.
  sdk="$(git rev-parse --show-toplevel)/.fvm/flutter_sdk"

  "$sdk/bin/dart" fix --apply .
  "$sdk/bin/dart" format $dart_files
  git add -- $dart_files

  # Analyze the workspace to catch errors before committing.
  "$sdk/bin/flutter" analyze
fi

# Format staged JSON, YAML, and Markdown files with prettier and include the results in this commit.
prettier_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.json' '*.yaml' '*.yml' '*.md')

if [ -n "$prettier_files" ]; then
  npx prettier -w $prettier_files
  git add -- $prettier_files
fi
