version: "2"

run:
  build-tags:
    - integration

linters:
  enable:
    - exhaustive
    - lll
    - sqlclosecheck
    - rowserrcheck
    - bodyclose
    - errorlint
    - misspell
    - modernize
  settings:
    exhaustive:
      check:
        - switch
        - map
    lll:
      line-length: 120

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
