// TODO: Garbage-collect expired tokens
package user

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"database/sql"
	_ "embed"
	"encoding/base64"
	"errors"
	"fmt"
	"html/template"
	"math/big"
	"net/mail"
	"regexp"
	"strings"
	"time"
	"unicode"

	"github.com/fujidaiti/paperdoll/server/infra"
	"golang.org/x/crypto/bcrypt"
)

var (
	ErrDeviceEmpty       = errors.New("device is empty")
	ErrEmailInvalid      = errors.New("email has invalid format")
	ErrEmailTaken        = errors.New("email already exists")
	ErrPswdInvalid       = errors.New("password has invalid format")
	ErrAuthFailed        = errors.New("email or password is incorrect")
	ErrTokenInvalid      = errors.New("token is invalid")
	ErrTooManyAttempts   = errors.New("too many attempts")
	ErrCodeInvalid       = errors.New("verification code has invalid format")
	ErrEmailVerifyFailed = errors.New("can not verify email address")
	ErrTokenExpired      = errors.New("token is expired")
)

// TODO: re-define this as a named type
type UserID = int

// TODO: re-define this as a named type of string
type ValidPassword struct{ value string }

// Printable ASCII characters only; 15-64 characters
var passwordRegex = regexp.MustCompile(`^[\x20-\x7E]{15,64}$`)

func ValidatePassword(p string) (ValidPassword, error) {
	if !passwordRegex.MatchString(p) {
		return ValidPassword{}, ErrPswdInvalid
	}
	return ValidPassword{p}, nil
}

func (p ValidPassword) Hash() ([]byte, error) {
	const cost = 12
	return bcrypt.GenerateFromPassword([]byte(p.value), cost)
}

// Match returns true if the hash of this password matches passwordHash,
// which must be generated by [ValidPassword.Hash].
func (p ValidPassword) Match(passwordHash []byte) bool {
	return bcrypt.CompareHashAndPassword(passwordHash, []byte(p.value)) == nil
}

// TODO: Rename to CanonicalEmailAddr
// TODO: re-define this as a named type of string
type CanonicalEmail struct{ value string }

func ParseEmail(addr string) (CanonicalEmail, error) {
	for i := 0; i < len(addr); i++ {
		if addr[i] > unicode.MaxASCII {
			return CanonicalEmail{}, ErrEmailInvalid
		}
	}
	a, err := mail.ParseAddress(addr)
	if err != nil || a.Address != addr {
		return CanonicalEmail{}, ErrEmailInvalid
	}
	return CanonicalEmail{strings.ToLower(a.Address)}, nil
}

type Token [32]byte

func NewToken() (Token, error) {
	t := Token{}
	_, err := rand.Read(t[:])
	return t, err
}

func DecodeToken(t string) (Token, error) {
	b, err := base64.RawURLEncoding.DecodeString(t)
	if err != nil || len(b) != 32 {
		return Token{}, ErrTokenInvalid
	}
	return Token([32]byte(b)), nil
}

func (t Token) Encode() string {
	if t == (Token{}) {
		return ""
	}
	return base64.RawURLEncoding.EncodeToString(t[:])
}

func (t Token) Hash() []byte {
	if t == (Token{}) {
		return nil
	}
	h := sha256.Sum256(t[:])
	return h[:]
}

type VerificationCode string

type VerificationCodeGenerator = func() (VerificationCode, error)

var verificationCodeRegex = regexp.MustCompile(`^\d{6}$`)

func ParseVerificationCode(code string) (VerificationCode, bool) {
	if verificationCodeRegex.MatchString(code) {
		return VerificationCode(code), true
	}
	return "", false
}

func NewVerificationCode() (VerificationCode, error) {
	n, err := rand.Int(rand.Reader, big.NewInt(1_000_000))
	if err != nil {
		return "", err
	}
	return VerificationCode(fmt.Sprintf("%06d", n)), nil
}

func (c VerificationCode) Hash() []byte {
	if c == "" {
		return nil
	}
	h := sha256.Sum256([]byte(c))
	return h[:]
}

// Match returns true if the hash of this code matches the codeHash,
// which must be generated by [VerificationCode.Hash].
func (c VerificationCode) Match(codeHash []byte) bool {
	return subtle.ConstantTimeCompare(c.Hash(), codeHash) == 1
}

//go:embed template/verification_email.html
var verificationEmailTmplSrc string
var verificationEmailTmpl = template.Must(
	template.New("verification_email").Parse(verificationEmailTmplSrc),
)

func (s *Service) SignUp(
	ctx context.Context, email CanonicalEmail, pswd ValidPassword,
) (Token, error) {
	return SignUp(ctx, email, pswd, s.DB, s.Now(), NewVerificationCode, s.SendEmail)
}

func SignUp(
	ctx context.Context, email CanonicalEmail, pswd ValidPassword,
	db *sql.DB, currentTime time.Time,
	generateCode VerificationCodeGenerator,
	emailSender infra.EmailSender,
) (Token, error) {
	pswdHash, err := pswd.Hash()
	if err != nil {
		return Token{}, err
	}
	return issueSignUpTicket(
		ctx, email.value, pswdHash, db, currentTime, generateCode, emailSender,
	)
}

func (s *Service) ResendSignUpVerificationEmail(
	ctx context.Context, ticket string,
) (Token, error) {
	return ResendSignUpVerificationEmail(
		ctx, ticket, s.DB, s.Now(), NewVerificationCode, s.SendEmail,
	)
}

func ResendSignUpVerificationEmail(
	ctx context.Context, ticket string, db *sql.DB, currentTime time.Time,
	generateCode VerificationCodeGenerator, emailSender infra.EmailSender,
) (Token, error) {
	tkt, err := DecodeToken(ticket)
	if err != nil {
		return Token{}, ErrTokenInvalid
	}

	var (
		email     string
		pswdHash  []byte
		expiresAt time.Time
	)
	err = db.QueryRowContext(ctx, `
		SELECT email, password_hash, expires_at
		FROM signup_tickets WHERE ticket_hash = $1
	`, tkt.Hash()).Scan(&email, &pswdHash, &expiresAt)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return Token{}, ErrTokenInvalid
	case err != nil:
		return Token{}, fmt.Errorf("failed to look up a ticket: %w", err)
	case currentTime.After(expiresAt):
		return Token{}, ErrTokenExpired
	}

	return issueSignUpTicket(ctx, email, pswdHash, db, currentTime, generateCode, emailSender)
}

func issueSignUpTicket(
	ctx context.Context, email string, passwordHash []byte, db *sql.DB,
	now time.Time, generateCode VerificationCodeGenerator, emailSender infra.EmailSender,
) (Token, error) {
	const ticketTTL = 10 * time.Minute
	const throttleWindow = time.Hour
	const throttleCap = 3

	var emailExists bool
	err := db.QueryRowContext(ctx, `
		SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
	`, email).Scan(&emailExists)
	switch {
	case err != nil:
		return Token{}, fmt.Errorf("can not verify email uniquness")
	case emailExists:
		return Token{}, ErrEmailTaken
	}

	var nIssued int
	err = db.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM signup_tickets
		WHERE email = $1 AND issued_at >= $2
	`, email, now.Add(-1*throttleWindow)).Scan(&nIssued)
	switch {
	case err != nil:
		return Token{}, fmt.Errorf("failed to count issued tickets: %w", err)
	case nIssued >= throttleCap:
		return Token{}, ErrTooManyAttempts
	}

	expiresAt := now.Add(ticketTTL)
	ticket, err := NewToken()
	if err != nil {
		return Token{}, fmt.Errorf("failed to generate sign-up verirication ticket: %w", err)
	}
	code, err := generateCode()
	if err != nil {
		return Token{}, fmt.Errorf("failed to generate sign-up verification code: %w", err)
	}

	var tID int
	err = db.QueryRowContext(ctx, `
		INSERT INTO signup_tickets
			(email, password_hash, verification_code_hash, ticket_hash, expires_at, issued_at)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id
	`, email, passwordHash, code.Hash(), ticket.Hash(), expiresAt, now).Scan(&tID)
	if err != nil {
		return Token{}, fmt.Errorf("failed to register sign-up ticket: %w", err)
	}

	var buf bytes.Buffer
	err = verificationEmailTmpl.Execute(&buf, map[string]any{
		"Code":             code,
		"ExpiresInMinutes": ticketTTL / time.Minute,
	})
	if err != nil {
		return Token{}, fmt.Errorf("failed to write verification email body: %w", err)
	}
	err = emailSender.Send(infra.EmailDraft{
		To:      email,
		Subject: "Your verification code",
		Body:    buf.String(),
	})
	if err != nil {
		// Don't return the error and issue the ticket anyway, so that users can re-request
		// a verification email later without sending the address and password again.
		fmt.Printf("failed to send sign-up verification email; ticket ID: %d; error: %v", tID, err)
	}

	return ticket, nil
}

// VerifySignUpEmailAddress verifies the submitted email address and promotes it
// to a new account if confirmed. Clients call this after the user signs up and
// receives an email with a verification code.
//
// The email is verified only if the pair of ticket and code is correct, meaning
// both belong to the same sign-up ticket row.
//
// On a wrong code, the per-ticket fail count increases. Once it reaches the threshold,
// the ticket is dead: verification never succeeds again event with the correct code.
//
// Reports an [ErrTokenInvalid] if the ticket is malformed or no ticket row is associated
// with it, an [ErrTokenExpired] if the ticket is expired or dead, an [ErrCodeInvalid]
// if the code is malformed, and an [ErrEmailVerifyFailed] if the code is wrong.
func (s *Service) VerifySignUpEmailAddress(ctx context.Context, ticket, code, device string) (Token, error) {
	// The number of wrong codes that kills a ticket.
	const maxFailCount = 5

	if device == "" {
		return Token{}, ErrDeviceEmpty
	}
	if _, ok := ParseVerificationCode(code); !ok {
		return Token{}, ErrCodeInvalid
	}
	tkt, err := DecodeToken(ticket)
	if err != nil {
		return Token{}, ErrTokenInvalid
	}

	var (
		tID                int
		email              string
		pswdHash, codeHash []byte
		expiresAt          time.Time
		failCount          int
	)
	err = s.DB.QueryRowContext(ctx, `
		SELECT id, email, password_hash, verification_code_hash, expires_at, fail_count
		FROM signup_tickets WHERE ticket_hash = $1
	`, tkt.Hash()).Scan(&tID, &email, &pswdHash, &codeHash, &expiresAt, &failCount)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return Token{}, ErrTokenInvalid

	case err != nil:
		return Token{}, fmt.Errorf("failed to look up a ticket: %w", err)

	case failCount >= maxFailCount || s.Now().After(expiresAt):
		return Token{}, ErrTokenExpired
	}

	if !VerificationCode(code).Match(codeHash) {
		_, err := s.DB.ExecContext(ctx, `
			UPDATE signup_tickets
			SET fail_count = fail_count + 1 WHERE id = $1
		`, tID)
		if err != nil {
			fmt.Printf("failed to increase fail count: %v\n", err)
		}
		return Token{}, ErrEmailVerifyFailed
	}

	var uID UserID
	err = s.DB.QueryRowContext(ctx, `
		INSERT INTO users (email, password_hash) VALUES ($1, $2)
		ON CONFLICT (email) DO NOTHING RETURNING id
	`, email, pswdHash).Scan(&uID)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return Token{}, ErrEmailTaken
	case err != nil:
		return Token{}, fmt.Errorf("failed to create new account: %w", err)
	}

	return s.issueAuthToken(ctx, uID, device)
}

func (s *Service) SignIn(
	ctx context.Context, email CanonicalEmail, pswd, device string,
) (Token, error) {
	if device == "" {
		return Token{}, ErrDeviceEmpty
	}
	var pswdHash []byte
	var id int
	err := s.DB.QueryRowContext(ctx, `
		SELECT id, password_hash FROM users WHERE email = $1
	`, email.value).Scan(&id, &pswdHash)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return Token{}, ErrAuthFailed
	case err != nil:
		return Token{}, err
	}
	if !(ValidPassword{pswd}).Match(pswdHash) {
		return Token{}, ErrAuthFailed
	}
	return s.issueAuthToken(ctx, id, device)
}

func (s *Service) issueAuthToken(
	ctx context.Context, id UserID, device string,
) (Token, error) {
	const tokenExpiresInDays = 30

	token, err := NewToken()
	if err != nil {
		return Token{}, err
	}
	expr := s.Now().AddDate(0, 0, tokenExpiresInDays)
	_, err = s.DB.ExecContext(ctx, `
		INSERT INTO auth_tokens (user_id, device, token_hash, expires_at)
		VALUES ($1, $2, $3, $4)
	`, id, device, token.Hash(), expr)
	if err != nil {
		return Token{}, err
	}
	return token, nil
}

// SignOut revokes the encoded token t. The user who owns that token remains
// authorized as long as their other tokens are valid.
//
// This operation does not fail even if the token is invalid, but it may report
// an unknown error due to infrastructure issues.
func (s *Service) SignOut(ctx context.Context, t string) error {
	token, err := DecodeToken(t)
	if err != nil {
		return nil
	}
	_, err = s.DB.ExecContext(ctx, `
		DELETE FROM auth_tokens WHERE token_hash = $1
	`, token.Hash())
	return err
}

// VerifyAuthToken checks if the encoded token t is valid and finds the user who
// owns that token. Reports an [ErrTokenInvalid] if the token is malformed or no user
// is associated with it, and an [ErrTokenExpired] if the token is expired.
// TODO: Garbage-collect expired tokens
func (s *Service) VerifyAuthToken(ctx context.Context, t string) (UserID, error) {
	token, err := DecodeToken(t)
	if err != nil {
		return 0, err
	}
	var id UserID
	var expiresAt time.Time
	err = s.DB.QueryRowContext(ctx, `
		SELECT user_id, expires_at FROM auth_tokens WHERE token_hash = $1
	`, token.Hash()).Scan(&id, &expiresAt)
	switch {
	case errors.Is(err, sql.ErrNoRows):
		return 0, ErrTokenInvalid
	case err != nil:
		return 0, fmt.Errorf("failed to look up an auth token: %w", err)
	case s.Now().After(expiresAt):
		return 0, ErrTokenExpired
	}
	return id, nil
}
